apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 8.18.0
  http:
    service:
      spec:
        type: LoadBalancer
  nodeSets:
  - name: es-data
    count: 3
    config:
      node.roles: [ "master", "data", "ingest", "ml", "transform" ]
      xpack.ml.enabled: true
      node.store.allow_mmap: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        #storageClassName: standard
    podTemplate:
      metadata:
        labels:
          key: eck-arm
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 0.5
            limits:
              memory: 2Gi
              cpu: 1
  # - name: data
  #   count: 3
  #   config:
  #     node.roles: [ "data", "ingest", "ml", "transform" ]
  #     node.store.allow_mmap: false
  #   volumeClaimTemplates:
  #   - metadata:
  #       name: elasticsearch-data
  #     spec:
  #       accessModes:
  #       - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 20Gi
  #       storageClassName: standard
  #   podTemplate:
  #     metadata:
  #       labels:
  #         key: eck-arm
  #     spec:
  #       initContainers:
  #       - name: sysctl
  #         securityContext:
  #           privileged: true
  #         command: [ 'sh', '-c', 'sysctl -w vm.max_map_count=262144' ]
  #       containers:
  #       - name: elasticsearch
  #         resources:
  #           requests:
  #             memory: 2Gi
  #             cpu: 0.5
  #           limits:
  #             memory: 2Gi
  #             cpu: 1
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.18.0
  http:
    service:
      spec:
        type: LoadBalancer
  count: 1
  elasticsearchRef:
    name: elasticsearch
